name: Release
on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: Release @ NodeJS LTS - x86 - ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: recursive
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WHMCSMP_LOGIN: ${{ secrets.WHMCSMP_LOGIN }}
          WHMCSMP_PASSWORD: ${{ secrets.WHMCSMP_PASSWORD }}
          WHMCSMP_PRODUCTID: ${{ secrets.WHMCSMP_PRODUCTID }}
        run: npx semantic-release
